// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Vbq1snT1pFHkWRkL743no24ZSyo0C6g',
    appId: '1:422824054276:web:93b9a690515c86d1b66f51',
    messagingSenderId: '422824054276',
    projectId: 'zoom-clone-3228e',
    authDomain: 'zoom-clone-3228e.firebaseapp.com',
    storageBucket: 'zoom-clone-3228e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMRKetuv6GeuFaG6m_hhnAwYRWG20I5IU',
    appId: '1:422824054276:android:78edbe9a30f6c9e5b66f51',
    messagingSenderId: '422824054276',
    projectId: 'zoom-clone-3228e',
    storageBucket: 'zoom-clone-3228e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNS4LE3nHJutn3FmGsqsxqPOo9mRrGxDg',
    appId: '1:422824054276:ios:7ed74efd8917a6c7b66f51',
    messagingSenderId: '422824054276',
    projectId: 'zoom-clone-3228e',
    storageBucket: 'zoom-clone-3228e.appspot.com',
    iosClientId: '422824054276-ok09881mer6tscifjn93nctvaed22p8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNS4LE3nHJutn3FmGsqsxqPOo9mRrGxDg',
    appId: '1:422824054276:ios:7ed74efd8917a6c7b66f51',
    messagingSenderId: '422824054276',
    projectId: 'zoom-clone-3228e',
    storageBucket: 'zoom-clone-3228e.appspot.com',
    iosClientId: '422824054276-ok09881mer6tscifjn93nctvaed22p8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomClone',
  );
}
